Message.create(content: 'Hello')
Message.create(content: 'Hi')
Message.create(content: 'Welcome')
Message.create(content: 'Good to see you here')
Message.create(content: 'It\'s nice to see you here')
